# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
fr:
  languageCode: fr-FR
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/fr
  title: Homepage of Léa Bittmann

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-US
  contentDir: content/en
  title: Homepage of Lea Bittmann
  params:
  #  description: Site description in Chinese...
  #menu:
    #main:
      #- name: 传
        #url: '#about'
        #weight: 1
