# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Accueil
    url: '#about'
    weight: 10
  - name: Publications
    url: '#publications'
    weight: 20
  - name: Exposés
    url: '#talks'
    weight: 30
  - name: Conférences
    url: '#conferences'
    weight: 40
  - name: Enseignement
    url: '#teaching'
    weight: 50
  - name: Autres activités
    url: '#other_activities'
    weight: 60
  - name: Contact
    url: '#contact'
    weight: 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/cv.pdf
#    weight: 80
